---
reject_list:
  - Windows Malicious Software Removal Tool for Windows
  - \d{4}-\d{2} Cumulative Update for Windows Server 2016  

catagory:
  - Application 
  - Connectors 
  - Critical Updates
  - Definition Updates
  - Developer Kits
  - Feature Packs
  - Guidance
  - Security Updates
  - Service Packs
  - Tools
  - Update Rollups
  - Updates
  - Upgrades  

reboot_required: false 

install_all: false
install_cat: false
install_selected: false