---
- name: Patching Remote Windows systems
  hosts: all
  become: true
  become_method: runas
  become_user: SYSTEM 
  tasks:

    - debug:
        msg: "{{ install_cat }}"

    - name: Install all updates as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: "{{ reboot_required }}"
        log_path: C:\ansible_wu.txt
        reject_list: "{{ reject_list }}"
      when: "{{install_all|bool}}"   

    - name: Install all security, critical, and rollup updates without a scheduled task   
      ansible.windows.win_updates:
        category_names: "{{ catagory }}"
        reboot: "{{ reboot_required }}"
        reject_list: "{{ reject_list }}"
      when: "{{install_cat|bool}}"

    - name: Install only particular updates based on the KB numbers
      ansible.windows.win_updates:
        category_names: "{{ catagory }}"
        accept_list: "{{ accept_list }}"
        reject_list: "{{ reject_list }}"
        reboot: "{{ reboot_required }}"
      when: "{{install_selected|bool}}"          

      