---
- name: Check Windows updates and send via email
  hosts: windows
  gather_facts: true
  vars:
    email_sender: dmeonavneet@gmail.com
    email_recipient: nrathi@redhat.com
    smtp_server: smtp.gmail.com
    smtp_port: 587
    smtp_username: dmeonavneet@gmail.com
    smtp_password: "rbfqhoincpyouxqk"

  tasks:

    - name: Search for available Windows Updates
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: update_search
  
    - name: Display update information
      debug:
        msg: "Found {{ update_search.found_update_count }} updates."
      when: update_search.found_update_count > 0

    # - name: Show details of found updates
    #   debug:
    #     msg: "{{ item.title }}"
    #   loop: "{{ update_search.updates }}"
    #   when: update_search.found_update_count > 0
      
    - name: Create update report file
      copy:
        unsafe_writes: true
        dest: C:\ansible_update_list.txt
        content: |
          Updates found on {{ inventory_hostname }}:

          {% for update_id, update_info in update_search.updates.items() %}
          - Title: {{ update_info.title }}
            KB: {{ update_info.kb | join(', ') }}
            Categories: {{ update_info.categories | join(', ') }}
            Installed: {{ update_info.installed }}
            Downloaded: {{ update_info.downloaded }}
          {% else %}
          No updates available.
          {% endfor %}

    - name: Fetch update report to control node
      fetch:
        src: C:\ansible_update_list.txt
        dest: ./windows_updates/{{ inventory_hostname }}_updates.txt
        flat: yes

    - name: Send update report email
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        from: "{{ email_sender }}"
        subject: "Windows Update Report for {{ inventory_hostname }}"
        body: |
          Please find the list of available updates for {{ inventory_hostname }} attached.
        attach:
          - "./windows_updates/{{ inventory_hostname }}_updates.txt"
        secure: starttls
      delegate_to: localhost
