---
- name: Install MSU updates offline
  hosts: windows
  gather_facts: no
  tasks:

    - name: Copy patch to target
      ansible.windows.win_copy:
        src: /path/to/KB123456.msu
        dest: C:\temp\KB123456.msu

    - name: Install patch with wusa
      ansible.windows.win_command:
        command: wusa.exe C:\temp\KB123456.msu /quiet /norestart

    - name: Reboot if required
      ansible.windows.win_reboot:
        reboot_timeout: 1800
      when: ansible_windows_update_pending is defined
